function bj_ui()
bj_setup_paths();

props = struct( ...
  'numDecks', 6, ...
  'bankroll0', 1000, ...
  'tableMin', 10, ...
  'tableMax', 500, ...
  'baseBet', 10, ...
  'bjPayout', 1.5, ...
  'dealerStandS17', true, ...
  'allowDouble', false, ...
  'reshufflePen', 0.25, ...
  'seed', [] ...
);

state = bj_engine_init(props);

% Light modern palette
bg = [0.95 0.96 0.98];
card = [1.00 1.00 1.00];
textMain = [0.13 0.16 0.23];
textSub = [0.38 0.42 0.51];
primary = [0.09 0.48 0.95];
success = [0.07 0.63 0.38];
warn = [0.86 0.54 0.10];

fig = uifigure( ...
  'Name','Blackjack Martingale', ...
  'Color',bg, ...
  'Position',[80 80 1220 740]);

titleLbl = uilabel(fig, ...
  'Position',[24 698 560 28], ...
  'Text','Blackjack Martingale Tester', ...
  'FontSize',24, ...
  'FontWeight','bold', ...
  'FontColor',textMain);

subtitleLbl = uilabel(fig, ...
  'Position',[24 676 560 18], ...
  'Text','Risk dashboard with hand-by-hand tracking', ...
  'FontSize',13, ...
  'FontColor',textSub);

panelStatus = uipanel(fig, ...
  'Position',[24 586 350 78], ...
  'BackgroundColor',card, ...
  'BorderType','line', ...
  'HighlightColor',[0.85 0.87 0.92], ...
  'Title','Session');
lbl = uilabel(panelStatus,'Position',[12 30 326 24],'FontSize',13,'FontWeight','bold','FontColor',textMain);
lbl2 = uilabel(panelStatus,'Position',[12 8 326 22],'FontSize',12,'FontColor',textSub);

panelRisk = uipanel(fig, ...
  'Position',[24 510 350 64], ...
  'BackgroundColor',card, ...
  'BorderType','line', ...
  'HighlightColor',[0.85 0.87 0.92], ...
  'Title','Stop Status');
lblStop = uilabel(panelRisk,'Position',[12 14 326 24],'FontSize',12,'FontWeight','bold','FontColor',success);

panelPlayer = uipanel(fig, ...
  'Position',[24 284 350 214], ...
  'BackgroundColor',card, ...
  'BorderType','line', ...
  'HighlightColor',[0.85 0.87 0.92], ...
  'Title','Player');
txtPlayer = uitextarea(panelPlayer,'Position',[10 10 330 178],'Editable','off');
txtPlayer.FontName = 'Avenir Next';
txtPlayer.FontSize = 15;

panelDealer = uipanel(fig, ...
  'Position',[24 58 350 214], ...
  'BackgroundColor',card, ...
  'BorderType','line', ...
  'HighlightColor',[0.85 0.87 0.92], ...
  'Title','Dealer');
txtDealer = uitextarea(panelDealer,'Position',[10 10 330 178],'Editable','off');
txtDealer.FontName = 'Avenir Next';
txtDealer.FontSize = 15;

btnDeal = uibutton(fig,'push', ...
  'Text','Deal Next Hand', ...
  'Position',[394 24 190 44], ...
  'BackgroundColor',primary, ...
  'FontColor',[1 1 1], ...
  'FontWeight','bold', ...
  'ButtonPushedFcn', @(~,~) step());

btnAuto = uibutton(fig,'push', ...
  'Text','Auto x50', ...
  'Position',[596 24 130 44], ...
  'BackgroundColor',[0.16 0.18 0.22], ...
  'FontColor',[1 1 1], ...
  'FontWeight','bold', ...
  'ButtonPushedFcn', @(~,~) auto());

btnReset = uibutton(fig,'push', ...
  'Text','Reset', ...
  'Position',[738 24 100 44], ...
  'BackgroundColor',[0.90 0.91 0.94], ...
  'FontColor',textMain, ...
  'ButtonPushedFcn', @(~,~) reset());

chartPanel = uipanel(fig, ...
  'Position',[394 86 802 578], ...
  'BackgroundColor',card, ...
  'BorderType','line', ...
  'HighlightColor',[0.85 0.87 0.92], ...
  'Title','Bankroll Trajectory');

ax = uiaxes(chartPanel,'Position',[14 14 772 532]);
ax.Color = card;
ax.FontName = 'Avenir Next';
ax.FontSize = 12;
ax.XColor = textSub;
ax.YColor = textSub;
ax.GridColor = [0.86 0.88 0.92];
ax.GridAlpha = 1;
grid(ax,'on');
hold(ax,'on');

render();

  function step()
    state = bj_engine_step(state);
    render();
  end

  function auto()
    for i=1:50
      state = bj_engine_step(state);
    end
    render();
  end

  function reset()
    state = bj_engine_init(state.props);
    render();
  end

  function render()
    [pLoss,maxLoss,pStreak] = bj_bust_streak_est(state);

    lbl.Text = sprintf('Hand %d   Bankroll $%.0f   Next Bet $%.0f   W/L/P %d/%d/%d', ...
      state.handN,state.bankroll,state.betNext,state.wins,state.losses,state.pushes);

    lbl2.Text = sprintf('Loss rate %.3f   Max losses left %d   P(streak) %.4f', ...
      pLoss,maxLoss,pStreak);

    if state.stop.hit
      lblStop.Text = sprintf('STOPPED after %d consecutive losses',state.stop.lossesInRow);
      lblStop.FontColor = [0.76 0.17 0.15];
      btnDeal.Enable = 'off';
      btnAuto.Enable = 'off';
    else
      lblStop.Text = sprintf('Running   Current loss streak: %d',state.currentLossStreak);
      lblStop.FontColor = success;
      btnDeal.Enable = 'on';
      btnAuto.Enable = 'on';
    end

    if state.handN==0
      txtPlayer.Value="Waiting for first hand...";
      txtDealer.Value="Waiting for first hand...";
    else
      txtPlayer.Value=state.last.playerText;
      txtDealer.Value=state.last.dealerText;
    end

    cla(ax);
    if ~isempty(state.history.bankroll)
      x = 1:numel(state.history.bankroll);
      y = state.history.bankroll;
      area(ax,x,y,'FaceColor',[0.86 0.93 1.00],'EdgeColor','none');
      plot(ax,x,y,'-o', ...
        'Color',primary, ...
        'LineWidth',1.8, ...
        'MarkerSize',4, ...
        'MarkerFaceColor',[1 1 1], ...
        'MarkerEdgeColor',primary);
      if state.stop.hit
        scatter(ax,state.stop.handN,state.stop.bankroll,48,warn,'filled');
      end
      xlim(ax,[1,max(10,numel(x))]);
      ylim(ax,[max(0,min(y)-50),max(y)+80]);
    else
      xlim(ax,[1 10]);
      ylim(ax,[max(0,state.bankroll-50),state.bankroll+80]);
    end
  end
end
